# Generated by Django 3.2 on 2021-05-20 13:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_header', models.CharField(max_length=50, unique=True)),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('course_category', models.CharField(max_length=50)),
                ('course_author', models.CharField(max_length=50, null=True)),
                ('course_short_desc', models.CharField(max_length=100, null=True)),
                ('course_desc', models.CharField(max_length=5000, null=True)),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated_by', models.CharField(max_length=50, unique=True)),
                ('rating', models.CharField(max_length=100, null=True)),
                ('rating_comment', models.CharField(max_length=50, null=True)),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('course_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', to_field='course_header')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_header', models.CharField(default='', max_length=50, unique=True)),
                ('lesson_id', models.IntegerField(default=0, unique=True)),
                ('course_name', models.CharField(max_length=50)),
                ('lesson_name', models.CharField(max_length=50)),
                ('lesson_description', models.CharField(max_length=100, null=True)),
                ('lesson_video_link', models.CharField(max_length=50, null=True)),
                ('lesson_video_minute', models.IntegerField(default='30')),
                ('lesson_about', models.CharField(max_length=1000, null=True)),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('course_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', to_field='course_header')),
            ],
        ),
    ]
