# Generated by Django 3.2 on 2021-05-08 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_header', models.CharField(max_length=50, unique=True)),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('course_category', models.CharField(max_length=50, unique=True)),
                ('course_author', models.CharField(max_length=50, null=True)),
                ('course_short_desc', models.CharField(max_length=100, null=True)),
                ('course_desc', models.CharField(max_length=5000, null=True)),
                ('created_dt', models.DateTimeField(default=datetime.datetime(2021, 5, 8, 5, 13, 45), null=True)),
                ('updated_dt', models.DateTimeField(default=datetime.datetime(2021, 5, 8, 5, 13, 45), null=True)),
            ],
        ),
    ]
