# Generated by Django 3.2 on 2021-05-08 05:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_dt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 5, 18, 2), null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_dt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 5, 18, 2, 570329, tzinfo=utc), null=True),
        ),
    ]
