# Generated by Django 3.2 on 2021-05-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210521_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_hour',
            field=models.IntegerField(default='100'),
        ),
        migrations.AddField(
            model_name='course',
            name='quiz_count',
            field=models.IntegerField(default='10'),
        ),
    ]
