# Generated by Django 3.2 on 2021-05-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210521_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_pic_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
