# Generated by Django 3.2 on 2021-05-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_course_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='discussion_count',
            field=models.IntegerField(default='30'),
        ),
    ]
