# Generated by Django 3.2 on 2021-05-08 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20210508_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_dt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 6, 25, 45), null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_dt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 6, 25, 45), null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_about',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_video_link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
