# Generated by Django 3.2 on 2021-05-20 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_header', models.CharField(default='', max_length=50)),
                ('course_header', models.CharField(default='', max_length=50, unique=True)),
                ('question', models.CharField(max_length=150, null=True)),
                ('option_one', models.CharField(max_length=100, null=True)),
                ('option_two', models.CharField(max_length=100, null=True)),
                ('option_three', models.CharField(max_length=100, null=True)),
                ('option_four', models.CharField(max_length=100, null=True)),
                ('correct_option', models.CharField(max_length=100, null=True)),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_header', models.CharField(default='', max_length=50, unique=True)),
                ('quiz_name', models.CharField(max_length=50, unique=True)),
                ('quiz_desc', models.CharField(max_length=50)),
                ('quiz_no_of_question', models.CharField(max_length=50, null=True)),
                ('quiz_difculty_level', models.CharField(max_length=100, null=True)),
                ('quiz_rating', models.CharField(max_length=5000, null=True)),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('course_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', to_field='course_header')),
            ],
        ),
    ]
