# Generated by Django 3.2 on 2021-05-08 15:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0015_auto_20210508_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_name', models.CharField(max_length=50, unique=True)),
                ('discussion_desc', models.CharField(max_length=50)),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('course_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', to_field='course_header')),
            ],
        ),
    ]
