# Generated by Django 3.2 on 2021-05-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='discussion_header',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='discussion_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
