# Generated by Django 3.2 on 2021-05-12 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_varification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varification',
            name='mail_otp_counter',
        ),
        migrations.RemoveField(
            model_name='varification',
            name='phone_otp_counter',
        ),
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_otp', models.IntegerField(null=True)),
                ('phone_otp', models.IntegerField(null=True)),
                ('mail_otp_counter', models.IntegerField(null=True)),
                ('phone_otp_counter', models.IntegerField(null=True)),
                ('email_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
